/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Cyber-Kitchen Design System Colors
        'secondary-container': '#ff8a00',
        'on-surface-variant': '#3a4a44',
        'on-secondary': '#ffffff',
        'primary-container': '#00ffd1',
        'on-secondary-fixed': '#2f1500',
        'outline': '#6a7b74',
        'secondary-fixed-dim': '#ffb77f',
        'on-tertiary': '#ffffff',
        'surface-tint': '#006b57',
        'primary': '#006b57',
        'surface-dim': '#dadad9',
        'on-primary-fixed': '#002019',
        'surface': '#f9f9f9',
        'on-tertiary-container': '#b700a4',
        'on-secondary-fixed-variant': '#6f3900',
        'on-error-container': '#93000a',
        'tertiary-fixed': '#ffd7f0',
        'inverse-surface': '#2f3131',
        'on-secondary-container': '#613100',
        'on-surface': '#1a1c1c',
        'surface-container-high': '#e8e8e7',
        'on-tertiary-fixed-variant': '#840076',
        'tertiary': '#ad009b',
        'surface-bright': '#f9f9f9',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#f1f1f0',
        'outline-variant': '#b9cbc3',
        'primary-fixed-dim': '#00e0b7',
        'surface-variant': '#e2e2e2',
        'surface-container': '#eeeeed',
        'on-primary-fixed-variant': '#005141',
        'surface-container-lowest': '#ffffff',
        'error': '#ba1a1a',
        'tertiary-fixed-dim': '#fface8',
        'secondary': '#914c00',
        'primary-fixed': '#15ffd1',
        'secondary-fixed': '#ffdcc4',
        'tertiary-container': '#ffd7f0',
        'background': '#f9f9f9',
        'on-primary-container': '#00725c',
        'inverse-primary': '#00e0b7',
        'on-tertiary-fixed': '#3a0033',
        'on-error': '#ffffff',
        'surface-container-low': '#f4f3f3',
        'surface-container-highest': '#e2e2e2',
        'on-primary': '#ffffff',
        'on-background': '#1a1c1c',
        // Neon colors for borders
        'neon-cyan': '#00FFD1',
        'neon-orange': '#FF8A00',
        'neon-pink': '#FF00E5',
        'neon-yellow': '#FFD700',
      },
      fontFamily: {
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-caps': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-md': ['Epilogue', 'sans-serif'],
        'headline-lg': ['Epilogue', 'sans-serif'],
        'brand-title': ['Great Vibes', 'cursive'],
        sans: ['Plus Jakarta Sans', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'brand-title': ['42px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        '2xl': '1.5rem',
        'full': '9999px',
      },
      spacing: {
        'container-max': '1280px',
        'gutter': '24px',
        'margin-page': '40px',
        'unit': '8px',
        'card-padding': '24px',
        '18': '4.5rem',
        '88': '22rem',
      },
      maxWidth: {
        'container-max': '1280px',
        '8xl': '88rem',
        '9xl': '96rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
      },
      backdropBlur: {
        'md': '12px',
      },
      boxShadow: {
        'hard': '4px 4px 12px 0px rgba(0, 0, 0, 0.08)',
        'neon-cyan': '0 0 10px rgba(0, 255, 209, 0.3)',
        'neon-orange': '0 0 10px rgba(255, 138, 0, 0.3)',
        'neon-pink': '0 0 10px rgba(255, 0, 229, 0.3)',
      }
    },
  },
  plugins: [],
}